resources:
- name: calc-git-resource
  type: git
  source:
    branch: master
    uri: https://github.com/mderacc/concourse-ci-demo-calc
jobs:
- name: test-job
  plan:
    - get: calc-git-resource
      trigger: true
    - task: unit-test
      file: calc-git-resource/.pipeline/tasks/unit-test-task.yml
- name: build-job
  plan:
    - get: calc-git-resource
      passed: 
        - test-job
      trigger: true
    - task: build
      file: calc-git-resource/.pipeline/tasks/build-task.yml
    - task: promote
      file: calc-git-resource/.pipeline/tasks/upload-task.yml