---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: maven
inputs:
  - name: calc-git-resource
outputs:
  - name: build-output
run:
  path: sh
  args:
  - -exc
  - |
    cd calc-git-resource
    mvn install
    cp -r target/concourse-ci-demo-calc-1.0-SNAPSHOT.jar ../build-output